export * from './Core';
export * from './Services';
export * from './Works';
export * from './Projects';
export * from './Contact';
export * from './NavBar';
export * from './Hero';
export * from './Role';
export * from './About';